# ------------------------------------------------------
# Page tree
# ------------------------------------------------------
nav:
  - index.md
  - Getting Started:
    - Getting Started: pages/basics/index.md
    - Basics:
      - ‣ Feature Flag: pages/basics/feature.md
      - ‣ Feature Store: pages/basics/feature-store.md
      - ‣ Property Store: pages/basics/property-store.md
      - ‣ Architecture: pages/basics/architecture.md
      - ‣ Security: pages/basics/security.md
      - ‣ Flipping Strategy: pages/basics/flipping-strategy.md
    - Advanced:
      - ‣ Features Groups: pages/advanced/feature-groups.md
      - ‣ Aspect Oriented Programming: pages/advanced/aop.md
      - ‣ Caching: pages/advanced/caching.md
      - ‣ Spring Boot: pages/advanced/spring-boot.md
      - ‣ Command line interface: pages/advanced/cli.md
      - ‣ JMX Support: pages/advanced/jmx.md
    - Web:
      - ‣ Web Console: pages/web/console.md
      - ‣ Taglib: pages/web/taglib.md
      - ‣ Thymeleaf tags: pages/web/thymeleaf.md
      - ‣ REST Api: pages/web/apis.md
  
  - Store Configurations:
    - Architecture: pages/configuration.md
    - Stores: pages/stores/index.md
    - Flipping Strategies: pages/strategy/index.md
    - v2: pages/v2/index.md
    - web: pages/web/index.md


  - Spring applications:
      - Home: pages/spring/index.md

  - Sample Codes:
      - Home: pages/samples/index.md
      - Cheat: cheat.md
  
# ------------------------------------------------------
# Settings
# ------------------------------------------------------

# Project information
site_name: FF4j
site_url: https://ff4j.github.io
site_author: Cedrick Lunven
site_description: >-
 Documentation for FF4j

# Repository
repo_name: ff4j/ff4j-docs
repo_url: https://github.com/ff4j/ff4j-docs
edit_uri: ""

# Theme
theme:
 name: material
 language: en

 favicon: img/favicon.svg
 logo: img/favicon.ico
 custom_dir: docs/overrides

 features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
 palette:

    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

 include_search_page: false
 search_index_only: true

# Markdown Support
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  #- pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search
  - git-revision-date
  - mkdocs-video
  #- render_swagger

# Customization
extra:
  analytics:
    provider: google
    property: UA-99337757-1
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ff4j
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/clunven
    - icon: fontawesome/brands/discord
      link: https://discord.gg/WUQxSNmZ9h
